Update README.md with new video links
isRuslan/awesome-elm pull request #104
Opened 2016-11-22 00:41 UTC by gasperz

Added live coding videos from Aaron VonderHaar and Greg Ziegan

2016-11-22 15:46 UTC, isRuslan requested changes

2016-11-22 15:46 UTC, isRuslan commented on README.md
> +* [Aaron VonderHaar: Elm live coding videos ](https://www.youtube.com/user/gruen0) - Lots of live coding videos on youtube.
Let's link here on exact ElmLive youtube list: https://www.youtube.com/playlist?list=PLDA4wlOlLJvWSYo3KiEa4q4ETkXpTaKlw - because a lot of out-of-elm stuff in channel in general.

2016-11-22 17:41 UTC, gasperz commented on README.md
> +* [Aaron VonderHaar: Elm live coding videos ](https://www.youtube.com/user/gruen0) - Lots of live coding videos on youtube.
That is better, but ElmLive playlist is missing a lot Codevember videos. And not all, are in the Codevember playlist (https://www.youtube.com/playlist?list=PLDA4wlOlLJvXAEsJDje4hdLazsihZiQNf). Do you have any idea how to get them all in the nicest way possible?

2016-11-22 19:17 UTC, isRuslan commented on README.md
> +* [Aaron VonderHaar: Elm live coding videos ](https://www.youtube.com/user/gruen0) - Lots of live coding videos on youtube.
Ok, let it be 2 links in one row:
[Aaron VonderHaar: Codevember 2016](https://www.youtube.com/playlist?list=PLDA4wlOlLJvXAEsJDje4hdLazsihZiQNf) + [ElmLive](https://www.youtube.com/playlist?list=PLDA4wlOlLJvWSYo3KiEa4q4ETkXpTaKlw) - elm live video examples

2016-11-23 13:21 UTC, isRuslan approved these changes

2016-11-23 13:21 UTC, merged

2016-11-23 13:21 UTC, isRuslan commented
Thanks!