Add Elm Europe 2017 and 2018 playlists in the videos section
isRuslan/awesome-elm pull request #153
Opened 2018-07-21 10:09 UTC by jlengrand

2018-07-22 23:08 UTC, laughedelic requested changes

2018-07-22 23:08 UTC, laughedelic commented on README.md
> +* [Elm Europe 2018](https://www.youtube.com/watch?v=uGlzRt-FYto&list=PL-cYi7I913S-VgTSUKWhrUkReM_vMNQxG) - A playlist of all talks from Elm Europe 2018
I think you need to put a newline after the list. Otherwise Github will render the link up on the same line

2018-07-22 23:08 UTC, laughedelic commented on README.md
> +* [Elm Europe 2017](hhttps://www.youtube.com/watch?v=XpDsk374LDE&list=PL-cYi7I913S8cGyZWdN6YVZ028iS9BfpM) - A playlist of all talks from Elm Europe 2017
A typo in the URL: `hhttps`

2019-07-22 04:13 UTC, sporto commented
Added

2019-07-22 04:13 UTC, closed without merging